
<script src="/typelib/String/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Long/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Double/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Date/res/editor.js" type="text/javascript"></script>
<script src="/typelib/RichText/res/editor.js" type="text/javascript"></script>
<script src="/typelib/HyperLink/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Enum/res/editor.js" type="text/javascript"></script>
<script src="/typelib/MultiSelect/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Tree/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Expression/res/editor.js" type="text/javascript"></script>
<script src="/typelib/ChemStructure/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Files/res/editor.js" type="text/javascript"></script>
<script src="/typelib/GpsLocation/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Reference/res/editor.js" type="text/javascript"></script>
<script src="/typelib/Collection/res/editor.js" type="text/javascript"></script>
