<table height=24 cellspacing=0 cellpadding=0 width=100% border=0>
  <tbody>
    <tr>
      <td height=24 align="center">
		 


<dl id="horizontalFrame">
	








<dd id='horizontalBody' class='basebat' >
		<div style="width:100%;" id="horizontalBodyInner">
			
													
<link rel="stylesheet" type="text/css" href="/console/shared/plugins/dhtmlx/menu/skins/dhtmlxmenu_dhx_blue.css">
<script src="/console/shared/plugins/dhtmlx/menu/dhtmlxmenu.js"></script>

<div id="menuObj_horizontal"></div>

<script type="text/javascript">

		if($('#menuObj_horizontal').html() == ''){

		var menu = new dhtmlXMenuObject("menuObj_horizontal");
		menu.setIconsPath("/console/shared/plugins/dhtmlx/menu/imgs/");
		menu.setSkin('dhx_blue');
	    menu.loadXMLString("<?xml version='1.0'?><menu id='0'><item id='1272529174765'  text='首页|/page/index.vpage'></item><item id='staticNode1446210706077'  text='1+1助学|/page/showItem.vpage?id=cms.news/1'></item><item id='staticNode1446902450986'  text='阳光大事记|/page/showEntity.vpage?uri=cms.news&amp;type=新闻动态'></item><item id='1274756981093'  text='资助学生信息|/page/showEntity.vpage?uri=ygzx.persons'></item><item id='staticNode1446902649902'  text='项目捐助|/page/showEntity.vpage?uri=ygzx.projects'></item><item id='staticNode1446902674301'  select='1' text='财务公开|/page/showItem.vpage?id=cms.news/15'></item><item id='staticNode1446211924447'  text='关于阳光助学|/page/showItem.vpage?id=cms.news/2'></item></menu>");
	}
	</script>					</div>
</dd>
</dl>      </td>
    </tr>
  </tbody>
</table>