/*
===================================================================
Copyright DHTMLX LTD. http://www.dhtmlx.com
This code is obfuscated and not allowed for any purposes except 
using on sites which belongs to DHTMLX LTD.

Please contact sales@dhtmlx.com to obtain necessary 
license for usage of dhtmlx components.
===================================================================
*/function eXcell_clist(cell){try{this.cell=cell;this.grid=this.cell.parentNode.grid}catch(er){};this.edit=function(){this.val=this.getValue();var a=(this.cell.cl||this.grid.clists[this.cell._cellIndex]);if(!a)return;this.obj=document.createElement("DIV");var b=this.val.split(",");var text="";for(var i=0;i<a.length;i++){var fl=false;for(var j=0;j<b.length;j++)if(a[i]==b[j])fl=true;if(fl)text+="<div><input type='checkbox' checked='true' /><label>"+a[i]+"</label></div>";else text+="<div><input type='checkbox' id='ch_lst_"+i+"'/><label>"+a[i]+"</label></div>"};text+="<div><input type='button' value='Apply' style='width:100px;font-size:8pt;' onclick='this.parentNode.parentNode.editor.grid.editStop();'/></div>";this.obj.editor=this;this.obj.innerHTML=text;document.body.appendChild(this.obj);this.obj.style.position="absolute";this.obj.className="dhx_clist";this.obj.onclick=function(e){(e||event).cancelBubble=true;return true};var kw=this.grid.fI(this.cell);this.obj.style.left=kw[0]+"px";this.obj.style.top=kw[1]+this.cell.offsetHeight+"px";this.obj.getValue=function(){var text="";for(var i=0;i<this.childNodes.length-1;i++)if(this.childNodes[i].childNodes[0].checked){if(text)text+=",";text+=this.childNodes[i].childNodes[1].innerHTML};return text}};this.getValue=function(){if(this.cell.mG)return "";return this.cell.innerHTML.toString().PA()};this.detach=function(val){if(this.obj){this.setValue(this.obj.getValue());this.obj.editor=null;this.obj.parentNode.removeChild(this.obj);this.obj=null};return this.val!=this.getValue()}};eXcell_clist.prototype=new gD;eXcell_clist.prototype.setValue=function(val){if(typeof(val)=="object"){var hJ=this.grid.bA.et("./option",val);if(hJ.length)this.cell.cl=[];for(var j=0;j<hJ.length;j++)this.cell.cl.push(hJ[j].firstChild?hJ[j].firstChild.data:"");val=val.firstChild.data};if(val===""||val===this.undefined){this.setCTxtValue(" ",val);this.cell.mG=true}else{this.dq(val);this.cell.mG=false}};D.prototype.AO=function(col,list){if(!this.clists)this.clists=new Array();if(typeof(list)!="object")list=list.split(",");this.clists[col]=list};