/*
===================================================================
Copyright DHTMLX LTD. http://www.dhtmlx.com
This code is obfuscated and not allowed for any purposes except 
using on sites which belongs to DHTMLX LTD.

Please contact sales@dhtmlx.com to obtain necessary 
license for usage of dhtmlx components.
===================================================================
*/D.prototype.enableMarkedCells=function(fl){this.markedRowsArr=new cD(0);this.markedCellsArr=new Array(0);this.lastMarkedRow=null;this.lastMarkedColumn=null;this.markedCells=true;this.lastMarkMethod=0;if(arguments.length>0){if(!K(fl))this.markedCells=false}};D.prototype.doMark=function(el,markMethod){var _rowId=el.parentNode.idd;var _cellIndex=el._cellIndex;if(!markMethod)markMethod=0;if(markMethod==0){this.unmarkAll()}else if(markMethod==1){if(this.lastMarkedRow){var r_start=Math.min(this.getRowIndex(_rowId),this.getRowIndex(this.lastMarkedRow));var r_end=Math.max(this.getRowIndex(_rowId),this.getRowIndex(this.lastMarkedRow));var c_start=Math.min(_cellIndex,this.lastMarkedColumn);var c_end=Math.max(_cellIndex,this.lastMarkedColumn);for(var i=r_start;i<r_end+1;i++){for(var j=c_start;j<c_end+1;j++){this.mark(this.bB(i),j,true)}}}}else if(markMethod==2){if(this.markedRowsArr.bP(_rowId)!= -1){for(var ci=0;ci<this.markedCellsArr[_rowId].length;ci++){if(this.markedCellsArr[_rowId][ci]==_cellIndex){this.mark(_rowId,_cellIndex,false);return true}}}};if(!this.markedCellsArr[_rowId])this.markedCellsArr[_rowId]=new cD(0);if(markMethod!=1)this.mark(_rowId,_cellIndex);this.HZ(this.cells(_rowId,_cellIndex).cell);this.lastMarkedRow=_rowId;this.lastMarkedColumn=_cellIndex;this.lastMarkMethod=markMethod;return true;};D.prototype.mark=function(Mj,cindex,fl){if(arguments.length>2){if(!K(fl)){this.cells(Mj,cindex).cell.className=this.cells(Mj,cindex).cell.className.replace(/cellselected/g,"");if(this.markedRowsArr.bP(Mj)!= -1){var ci=this.markedCellsArr[Mj].bP(cindex);if(ci!= -1){this.markedCellsArr[Mj].hd(ci);if(this.markedCellsArr[Mj].length==0){this.markedRowsArr.hd(this.markedRowsArr.bP(Mj))};this.callEvent("onCellUnMarked",[Mj,cindex])}};return true}};this.cells(Mj,cindex).cell.className+=" cellselected";if(this.markedRowsArr.bP(Mj)== -1)this.markedRowsArr[this.markedRowsArr.length]=Mj;if(!this.markedCellsArr[Mj])this.markedCellsArr[Mj]=new cD(0);if(this.markedCellsArr[Mj].bP(cindex)== -1){this.markedCellsArr[Mj][this.markedCellsArr[Mj].length]=cindex;this.callEvent("onCellMarked",[Mj,cindex])}return true;};D.prototype.unmarkAll=function(){if(this.markedRowsArr){for(var ri=0;ri<this.markedRowsArr.length;ri++){var Mj=this.markedRowsArr[ri];for(var ci=0;ci<this.markedCellsArr[Mj].length;ci++){this.callEvent("onCellUnMarked",[Mj,this.markedCellsArr[Mj][ci]]);this.cells(Mj,this.markedCellsArr[Mj][ci]).cell.className=this.cells(Mj,this.markedCellsArr[Mj][ci]).cell.className.replace(/cellselected/g,"")}};this.markedRowsArr=new cD(0);this.markedCellsArr=new Array(0)};return true};D.prototype.getMarked=function(){var marked=new Array();for(var ri=0;ri<this.markedRowsArr.length;ri++){var Mj=this.markedRowsArr[ri];for(var ci=0;ci<this.markedCellsArr[Mj].length;ci++){marked[marked.length]=[Mj,this.markedCellsArr[Mj][ci]]}};return marked};