package vdb.litesync.summary;

import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.util.List;

import cn.csdb.commons.util.FileUtils;
import cn.csdb.commons.util.TimeUtils;

public class SummaryWriter
{
	private File _file;

	public SummaryWriter(File file)
	{
		_file = file;
	}

	public void write(Summary summary) throws IOException
	{
		StringWriter writer = new StringWriter();
		writer.write(String.format("###summary file generated by %s\r\n", this
				.getClass().getName()));

		List<SummaryEntry> entries = summary.getEntries();

		writer.write(String.format(
				"###summarize at: %s, total entries: %d\r\n", TimeUtils
						.getNowString(), entries.size()));

		for (SummaryEntry entry : entries)
		{
			writer.write(String.format("%s\t%s\t%s\t%s\r\n", entry.getPath(),
					"" + entry.getKind(), "" + entry.getLength(), entry
							.getDigest()));
		}

		writer.close();

		if (!_file.exists())
		{
			_file.getParentFile().mkdirs();
		}
		else
		{
			_file.delete();
		}

		_file.createNewFile();
		FileUtils.saveFile(writer.toString(), _file);

		_file.setReadOnly();
	}
}
